use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct SupportedCountriesManifest {
    alpha2: Vec<String>,
}

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let data_dir = Path::new(&manifest_dir).join("data");

    println!("cargo:rerun-if-changed=data/");

    let countries_path = data_dir.join("supported-countries-alpha2.json");
    let countries_json = fs::read_to_string(&countries_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", countries_path.display()));
    let countries: SupportedCountriesManifest = serde_json::from_str(&countries_json)
        .unwrap_or_else(|e| panic!("parse {}: {e}", countries_path.display()));

    let adjectives_path = data_dir.join("handle-adjectives.json");
    let adjectives_json = fs::read_to_string(&adjectives_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", adjectives_path.display()));
    let adjectives: Vec<String> = serde_json::from_str(&adjectives_json)
        .unwrap_or_else(|e| panic!("parse {}: {e}", adjectives_path.display()));

    let animals_path = data_dir.join("handle-animals.json");
    let animals_json = fs::read_to_string(&animals_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", animals_path.display()));
    let animals: Vec<String> = serde_json::from_str(&animals_json)
        .unwrap_or_else(|e| panic!("parse {}: {e}", animals_path.display()));

    let mut out = String::from("// @generated by build.rs — do not edit\n\n");
    write_str_slice(&mut out, "SUPPORTED_COUNTRIES_ALPHA2", &countries.alpha2);
    write_str_slice(&mut out, "HANDLE_ADJECTIVES", &adjectives);
    write_str_slice(&mut out, "HANDLE_ANIMALS", &animals);

    let generated = Path::new(&out_dir).join("generated.rs");
    fs::write(&generated, out).unwrap_or_else(|e| panic!("write {}: {e}", generated.display()));
}

fn write_str_slice(out: &mut String, name: &str, items: &[String]) {
    out.push_str(&format!("pub const {name}: &[&str] = &[\n"));
    for item in items {
        let escaped = item.replace('\\', "\\\\").replace('\"', "\\\"");
        out.push_str(&format!("    \"{escaped}\",\n"));
    }
    out.push_str("];\n\n");
}
